-- 1. 학생(Students) 테이블 생성
CREATE TABLE public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  school text,
  grade text,
  goal text,
  "parentType" text,
  sensitivity text,
  "lastReport" text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 학생 초기 데이터 삽입 (원하시는 경우만 실행하세요)
INSERT INTO public.students (name, school, grade, goal, "parentType", sensitivity, "lastReport") VALUES
('김민준', '강남중', '중2', '성적향상', '분석형', '보통', '2026-04-30'),
('이지은', '서초중', '중1', '흥미유발', '격려형', '낮음', '2026-05-02'),
('박도윤', '역삼중', '중3', '선행진도', '결과중심형', '높음', '2026-04-28'),
('최유나', '대치중', '중2', '성적향상', '분석형', '보통', '2026-05-15'),
('정시우', '도곡중', '중1', '성적향상', '참여형', '낮음', '2026-05-10');


-- 3. 최근 분석 기록(Analyses) 테이블 생성
CREATE TABLE public.analyses (
  id bigint generated by default as identity primary key,
  name text not null,
  school text,
  test text,
  date text,
  score integer,
  weakness text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. 분석 기록 초기 데이터 삽입 (원하시는 경우만 실행하세요)
INSERT INTO public.analyses (name, school, test, date, score, weakness) VALUES
('김민준', '강남중', '2026 1학기 중간고사', '방금 전', 85, '이차방정식 활용'),
('이지은', '서초중', '2026 1학기 중간고사', '2시간 전', 72, '인수분해'),
('박도윤', '역삼중', '2025 2학기 기말고사', '어제', 90, '계산 실수');


-- 5. RLS(Row Level Security) 설정 (프론트엔드에서 바로 읽고 쓰기 위한 테스트용 권한 개방)
-- ※ 실제 상용 서비스 오픈 시에는 안전하게 권한을 재설정해야 합니다.
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read/write for all users" ON public.students FOR ALL USING (true);

ALTER TABLE public.analyses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read/write for all users" ON public.analyses FOR ALL USING (true);
